app/auth.py
from flask_mail import Mail, Message
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from models import User
from __init__ import db, mailer
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from itsdangerous import URLSafeTimedSerializer, SignatureExpired
import string, random

auth = Blueprint('auth', __name__)

s = URLSafeTimedSerializer('testSecret')

@auth.route('/login', methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('client_page.client'))  

    if request.method == "POST":
        email = request.form.get('email').lower()
        password = request.form.get('password')
        
        user = User.query.filter_by(email = email).first()
        if user:
            if check_password_hash(user.password, password) and user.emailConfirm:
                login_user(user, remember=True)
                session['email'] = email
                return redirect(url_for('client_page.client'))
            else:
                flash('Wrong email or password!', category='error')
        else:
            flash("No such email registered!", category='error')
    return render_template('logIn.html', user=current_user)


@auth.route('/logout', methods=["GET","POST"])
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))


@auth.route('/sign_up',methods=["GET","POST"])
def sign_up():
    if current_user.is_authenticated:
        return redirect(url_for('client_page.client'))  

    if request.method == "POST":
        email = request.form.get("email").lower()
        password = request.form.get('password')
        password_confirm = request.form.get('confirm')
        session['email'] = obfuscate_email(email)
        user = User.query.filter_by(email=email).first()
        token = s.dumps(email,  salt='email_confirm')

        if user:
            if not user.emailConfirm:
                link = url_for('auth.confirm_email', token=token, _external=True)
                try:
                    msg = Message(subject='Confirm Your Account', body=f'Please confirm your email: ' +link ,sender="viddatconfirm@gmail.com",recipients=[email])
                    mailer.send(msg)
                except Exception as e:
                    print("Error: " + str(e), flush=True)
                return redirect(url_for("auth.verifyEmail"))
            else:
                    flash("An account is already registered with this email!", category="error")
        elif len(email) < 5:
            flash("Email must be atleast 6 characters!", category="error")
        elif len(password) < 7:
            flash("Password must be atleast 8 characters!", category="error")
        elif password != password_confirm:
            flash("Passwords do not match!", category="error")
        else:
            new_user = User(email=email, emailConfirm=False, password = generate_password_hash(password, method='pbkdf2:sha256'), username="default", aws_secret="", aws_access="", profile_picture="../static/userProfile.png", password_reset="", custom_video="")
            db.session.add(new_user)
            db.session.commit()
            link = url_for('auth.confirm_email', token=token, _external=True)
            msg = Message(subject='Confirm Your Account', body=f'Please confirm your email: ' +link +" (This link is only valid for 10 minutes)." ,sender="viddatconfirm@gmail.com",recipients=[email])
            mailer.send(msg)
            return redirect(url_for("auth.verifyEmail"))

    return render_template("signUp.html", user=current_user)


@auth.route('/confirm_email/<token>')
def confirm_email(token):
    try:
        email = s.loads(token, salt='email_confirm', max_age=600)
    except SignatureExpired:
        return render_template("emailExpired.html")
    user = User.query.filter_by(email = email).first()
    user.emailConfirm = True
    db.session.commit()
    login_user(user, remember=True)
    return render_template('emailVerified.html', user=current_user)

@auth.route('/confirm_email/verify')
def verifyEmail():
    return  render_template('checkEmail.html')

@auth.route('/recover/', methods=['GET', 'POST'])
def recover():
    if request.method == "POST":
        email = request.form.get("email").lower()
        try:
            token = s.dumps(email, "reset_pwd")
            link = url_for('auth.forgot', token=token, _external=True)
            msg = Message(subject="Viddat Password Reset", body="You have requested to change your password, please follow this link to do so: "+link+" (This link is only valid for 10 mintues)",sender="viddatconfirm@gmail.com",recipients=[email])
            mailer.send(msg)
            user = User.query.filter_by(email=email).first()
            user.password_reset = token
            db.session.commit()
            flash("Password reset sent successfully!", category="success")
        except Exception as e:
            flash("Something went wrong!", category="error")
            print("Error: " +str(e),flush=True)
    return render_template("recover.html")


@auth.route('/forgot/<token>', methods =["GET","POST"])
def forgot(token):
    try:
        email = s.loads(token, salt="reset_pwd",max_age=600)
    except Exception as e:
        return render_template("forgot.html")
    
    if request.method == "POST":
        password = request.form.get('password')
        password_confirm = request.form.get('confirm')
        if len(password) < 7:
            flash("Password must be atleast 8 characters!", category="error")
        elif password != password_confirm:
            flash("Passwords do not match!", category="error")
        else:
            try:
                user = User.query.filter_by(email=email).first()
                if user.password_reset != token:
                    raise Exception("Wrong token")
                user.password = generate_password_hash(password, method='pbkdf2:sha256')
                db.session.commit()
                flash("Your password has updated successfully", category="success")
                user.password_reset = generate_random_string(6)
                db.session.commit()
            except Exception as e:
                flash("Something went wrong!", category="error")
    return render_template("forgot.html")


def obfuscate_email(email : str):
    i = len(email) -1
    while email[i] != "@":
        i-=1
    chars_before = i//2
    return email[0 :chars_before + 1] + "*"*(i-chars_before) + email[i:]

def generate_random_string(length=8):
    characters = string.ascii_letters + string.digits  # Includes both letters and numbers
    return ''.join(random.choice(characters) for _ in range(length))

app/views.py
from flask import Blueprint, render_template, redirect, url_for


views = Blueprint('views', __name__)    

@views.route('/')
def home():
    return render_template("home.html")

@views.route('/terms_of_service')
def tos():
    return render_template("terms_of_service.html")

@views.route("/privacy")
def privacy():
    return render_template("privacy.html")

# @views.route('/pricing')
# def pricing():
#     return render_template("home.html")

@views.route('/emailVerified')
def emailVerified():
    return render_template("emailVerified.html")

# @views.route('/test')
# def test():
#     return render_template("checkEmail.html")

# @views.route("/tutorial")
# def tutorial():
#     return render_template("how_to.html")

@views.route('/tutorial/<int:step>')
def tutorial(step):
    if step < 1 or step > 13:
        return redirect(url_for('client_page.client'))
    return render_template(f'vid-dat_tutorial-{step}.html')

app/templates/accountSettings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="../static/favicon.ico">
    <script>
        if ( window.history.replaceState ) {
            window.history.replaceState( null, null, window.location.href );
        }
    </script>
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='styles/accountSettings.css')}}" />
    <title>Viddat Home</title>
</head>
<body>
    <header>
        <div id="navbar">
            <header>    
                <nav>
                    <a href="{{ url_for('client_page.client') }}" class="logo"><h1 style="color: black;">Viddat</h1></a>
                    <ul class="nav_links">
                        <li><a href="{{url_for('client_page.status')}}">Your Video</a></li>
                        <li><a href="{{url_for('views.tutorial',step=1)}}">How To Use</a></li>
                        <li><a href="{{url_for('client_page.accountSettings')}}" style="margin-right: 20px;">Profile</a></li>
                    </ul>
                    <div class="profile" onclick="toggleMenu()">
                        <img src="{{current_user.profile_picture}}" class="user-pic" width="55px" height="55px" onerror="this.onerror=null; this.src='../static/loading.gif'">
                        <img src="../static/downArrow.svg" width="14" height="14" class="downArrow"> 
                    </div>

                    <div class="sub-menu-wrap" id="subMenu">
                        <div class="user-email">
                            <h2>{{current_user.email}}</h2>
                        </div>
                        <div class="sub-menu">
                            <div class="user-info ">
                                <a href="{{url_for('client_page.accountSettings')}}">
                                    <div class="account-settings">
                                        <img src="../static/settings.png" class="setting_gear" width="20px" height="20px" style="margin-top: 3px;">
                                        <h3 style="margin-left: 4px;">Account Settings</h3>
                                    </div>
                                </a>
                            </div>

                            <div class="logout">
                                <a href="{{ url_for('auth.logout') }}"><button class="logbutton">Log out</button></a>
                            </div>
                        </div>
                    </div>
                </nav>
                {% with messages = get_flashed_messages(category_filter=["error"])%}
                {% if messages%}
                    {% for message in messages%}
                    <div class="alert">
                        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                        {{message}}
                    </div>
                    {%endfor%}
                    {%endif%}
                    {%endwith%}
                {% with messages = get_flashed_messages(category_filter=["success"])%}
                {% if messages%}
                    {% for message in messages%}
                    <div class="alert_success">
                        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                        {{message}}
                    </div>
                    {%endfor%}
                    {%endif%}
                    {%endwith%}
            </header>
        </div>
    </header>
    
    

    <section style="background-color: #fff; height: 870px">
        <form enctype=multipart/form-data method="POST">
            <div class="sideNav">
                <div class="user-img">
                        <img src="{{current_user.profile_picture}}" id="photo" height="80px" width="80px" onerror="this.onerror=null; this.src='../static/loading.gif'">
                        <input 
                            type="file" 
                            class="file-uploader"
                            onchange="upload()"
                            accept="image/*"
                            id="pfp"
                            name="pfp"
                            >
                    <label for="file"><img src="../static/cam.png" height="10px" width="10px" id="uploadbtn"></label>
                    <script>
                        function upload() {
                            const fileUploadInput = document.querySelector('.file-uploader');

                            // using index [0] to take the first file from the array
                            const image = fileUploadInput.files[0];

                            // check if the file selected is not an image file
                            if (!image.type.includes('image')) {
                            return alert('Only images are allowed!');
                            }

                            // check if size (in bytes) exceeds 10 MB
                            if (image.size > 10*1024*1024) {
                                fileUploadInput.value= null;
                            return alert('Maximum upload size is 10MB!');
                            }     
                            const fileReader = new FileReader();
                            fileReader.readAsDataURL(image);

                            fileReader.onload = (fileReaderEvent) => {
                                const url = URL.createObjectURL(image)
                                document.getElementById("photo").src=url
                            }
                        }                                 
                    </script>
                </div>
                <div style="padding-top: 40px;">
                <a href="{{url_for('client_page.accountSettings')}}"><li style="color: #346DFF; font-weight: 500; background-color: #A2B9F4;">Account Settings</li></a>
                <a href="{{url_for('views.tos')}}"><li>Terms of Service</li></a>
                <a href="{{url_for('views.privacy')}}"><li>Privacy Policy</li></a>
                <!-- <a href="{{url_for('client_page.premiumSubscriptions')}}"><li>Premium Subscriptions</li></a>
                <a href="{{url_for('client_page.billingHistory')}}"><li>Billing History</li></a> -->
                </div>
            </div>

            <div class="accountSettingsParent">
                <h1 style="text-align: left; font-size: 30px;">Account Settings</h1>
                <p style="text-align: left; font-weight: 300; font-size: 18px;">View and update your account details, profile and more.</p>
                <p style="text-align: left; padding-bottom: 30px; font-weight: 300; font-size: 18px;"> Note: If you leave a field blank, it will not update whilst others will! </p>
                <div class="accountSettingsChild">
                    <div style="border-bottom: 1px solid #D3D3D3; padding: 20px 30px;">
                        <h1 style="text-align: left; font-size: 20px;">Account Info</h1>
                    </div>
                    <div style="padding: 30px;">
                            <label for="access">AWS Access Code</label>
                            <br>
                            <input type="password" id="access" name="access" autocomplete="off" placeholder="Required">
                            <br><br>
                            <label for="secret">AWS Secret Code</label>
                            <br>
                            <input type="password" id="secret" name="secret" autocomplete="off" placeholder="Required"> 
                            <br><br>
                            <label for="username">Username</label>
                            <br>
                            <input type="text" id="username" name="username" value="{{current_user.username}}">
                            <br>
                            <br>
                            <input type="submit" value="Save">
                            
                    </div> 
                </div>
            </div>
            
        </form>
        
    </section>

    <script>


        let subMenu = document.getElementById("subMenu");

        function toggleMenu() {
            subMenu.classList.toggle("open-menu");
        }
    </script>
</body>
</html>

app/templates/billingHistory.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/x-icon" href="../static/favicon.ico">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='styles/clientPage.css')}}" />
    <title>Viddat Home</title>
</head>
<body>
    <header>
        <div id="navbar">
            <header>    
                <nav>
                    <a href="{{ url_for('client_page.client') }}" class="logo"><h1 style="color: black;">Viddat</h1></a>
                    <ul class="nav_links">
                        <li><a href="{{url_for('views.pricing')}}">Statistics</a></li>
                        <li><a href="{{url_for('auth.login')}}" style="margin-right: 20px;">Profile</a></li>
                    </ul>
                    <div class="profile" onclick="toggleMenu()">
                        <img src="{{current_user.profile_picture}}" class="user-pic" width="55px" height="55px" onerror="this.onerror=null; this.src='../static/loading.gif'">
                        <img src="static/downArrow.svg" width="14" height="14" class="downArrow"> 
                    </div>

                    <div class="sub-menu-wrap" id="subMenu">
                        <div class="user-email">
                            <h2>{{current_user.email}}</h2>
                        </div>
                        <div class="sub-menu">
                            <div class="user-info ">
                                <a href="{{url_for('client_page.accountSettings')}}">
                                    <div class="account-settings">
                                        <img src="static/settings.png" class="setting_gear" width="20px" height="20px" style="margin-top: 3px;">
                                        <h3 style="margin-left: 4px;">Account Settings</h3>
                                    </div>
                                </a>
                            </div>

                            <div class="logout">
                                <a href="{{ url_for('auth.logout') }}"><button class="logbutton">Log out</button></a>
                            </div>
                        </div>
                    </div>
                </nav>
            </header>
        </div>
    </header>

    <section>
        <div class="sideNav">
                <a href="{{url_for('client_page.accountSettings')}}"><li>Account Settings</li></a>
                <a href="{{url_for('client_page.premiumSubscriptions')}}"><li>Premium Subscriptions</li></a>
                <a href="{{url_for('client_page.billingHistory')}}"><li style="color: #346DFF; font-weight: 500; background-color: #A2B9F4;">Billing History</li></a>
        </div>
    </section>

    <script>
        let subMenu = document.getElementById("subMenu");

        function toggleMenu() {
            subMenu.classList.toggle("open-menu");
        }
    </script>
</body>
</html>

app/templates/clientPage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/x-icon" href="../static/favicon.ico" />

    <link
      rel="stylesheet"
      type="text/css"
      href="{{url_for('static',filename='styles/clientPage.css')}}"
    />
    <title>Viddat Home</title>
  </head>
  <body>
    <header>
      <div id="navbar">
        <header>
          <nav>
            <a href="{{ url_for('client_page.client') }}" class="logo"
              ><h1 style="color: black">Viddat</h1></a
            >
            <ul class="nav_links">
              <li>
                <a href="{{url_for('client_page.status')}}">Your Video</a>
              </li>
              <li>
                <a href="{{url_for('views.tutorial', step=1)}}">How To Use</a>
              </li>
              <li>
                <a
                  href="{{url_for('client_page.accountSettings')}}"
                  style="margin-right: 20px"
                  >Profile</a
                >
              </li>
            </ul>
            <div class="profile" onclick="toggleMenu()">
              <img
                src="{{current_user.profile_picture}}"
                class="user-pic"
                width="55px"
                height="55px"
                onerror="this.onerror=null; this.src='../static/loading.gif'"
              />
              <img
                src="static/downArrow.svg"
                width="14"
                height="14"
                class="downArrow"
              />
            </div>

            <div class="sub-menu-wrap" id="subMenu">
              <div class="user-email">
                <h2>{{current_user.email}}</h2>
              </div>
              <div class="sub-menu">
                <div class="user-info">
                  <a href="{{url_for('client_page.accountSettings')}}">
                    <div class="account-settings">
                      <img
                        src="static/settings.png"
                        class="setting_gear"
                        width="20px"
                        height="20px"
                        style="margin-top: 3px"
                      />
                      <h3 style="margin-left: 4px">Account Settings</h3>
                    </div>
                  </a>
                </div>

                <div class="logout">
                  <a href="{{ url_for('auth.logout') }}"
                    ><button class="logbutton">Log out</button></a
                  >
                </div>
              </div>
            </div>
          </nav>
          {% with messages = get_flashed_messages(category_filter=["error"])%}
          {% if messages%} {% for message in messages%}
          <div class="alert">
            <span
              class="closebtn"
              onclick="this.parentElement.style.display='none';"
              >&times;</span
            >
            {{message}}
          </div>
          {%endfor%} {%endif%} {%endwith%} {% with messages =
          get_flashed_messages(category_filter=["success"])%} {% if messages%}
          {% for message in messages%}
          <div class="alert_success">
            <span
              class="closebtn"
              onclick="this.parentElement.style.display='none';"
              >&times;</span
            >
            {{message}}
          </div>
          {%endfor%} {%endif%} {%endwith%}
        </header>
      </div>
    </header>
    <form method="POST">
      <section class="clientLanding">
        <div class="createVideoWrapper">
          <h1>Create Video</h1>
          <textarea
            class="title"
            name="title"
            rows="4"
            cols="50"
            placeholder="Enter Video Title Here:"
          ></textarea>
          <br /><br />
          <textarea
            class="text"
            name="text"
            rows="4"
            cols="50"
            placeholder="Enter Video Text Here:"
          ></textarea>
          <br /><br />
          <div class="partSelector">
            <div style="width: fit-content">
              <label for="part">(Optional) Red Highlighted Text</label
              ><br /><br />
              <textarea
                class="redtitle"
                name="part"
                rows="4"
                cols="30"
                placeholder="Enter Red Highlighted Text Here:"
              ></textarea>
              <br /><br />
            </div>
            <div style="margin-left: 20%; width: 40%">
              <p>Narrator Gender:</p>
              <label for="gender" style="font-size: small">
                A gender will be inferred through the text if one is not
                provided!</label
              >
              <br />
              <span>Male</span>
              <input type="radio" name="gender" value="999999" />
              <span>Female</span>
              <input type="radio" name="gender" value="-999999" />
            </div>
          </div>
          <div class="additional_attributes">
            <div class="inner_container">
              <input name="music" type="radio" value="True" />
              <label style="padding-left: 3px"> Add Background Music</label>
            </div>
            <div class="inner_container"></div>
          </div>
          <input
            class="createButton"
            type="submit"
            value="Create Video"
          /><br /><br />
        </div>
        <div class="myVideosWrapper">
          <h1>Background Footage</h1>
          <div id="videos">
            <div class="video_box">
              <img
                src="../static/minecraft_cover.png"
                class="display_img"
                alt=""
              />
              <label class="container"
                >Minecraft
                <input
                  class="video-selection"
                  type="checkbox"
                  name="videos"
                  value="stock_footage/minecraft/"
                />
                <span class="checkmark"></span>
              </label>
            </div>
            <div class="video_box">
              <img src="../static/mirrorsedge.jpg" class="display_img" alt="" />
              <label class="container"
                >Mirrors Edge
                <input
                  class="video-selection"
                  type="checkbox"
                  name="videos"
                  value="stock_footage/mirrors_edge"
                />
                <span class="checkmark"></span>
              </label>
            </div>
            <div class="video_box">
              <img src="../static/IRL.jpg" class="display_img" alt="" />
              <label class="container"
                >IRL
                <input
                  class="video-selection"
                  type="checkbox"
                  name="videos"
                  value="stock_footage/irl/"
                />
                <span class="checkmark"></span>
              </label>
            </div>
            <div class="video_box">
              <img src="../static/cooking.webp" class="display_img" alt="" />
              <label class="container"
                >Cooking
                <input
                  class="video-selection"
                  type="checkbox"
                  name="videos"
                  value="stock_footage/cooking/"
                />
                <span class="checkmark"></span>
              </label>
            </div>
            <div class="video_box">
              <img src="../static/trackmania.jpg" class="display_img" alt="" />
              <label class="container"
                >Trackmania
                <input
                  class="video-selection"
                  type="checkbox"
                  name="videos"
                  value="stock_footage/trackmania/"
                />
                <span class="checkmark"></span>
              </label>
            </div>
            <div class="video_box">
              <img src="../static/upload_video.png" alt="" />
              <label class="container"
                >Custom Video
                <input
                  type="checkbox"
                  name="videos"
                  class="video-selection"
                  value="Custom Video"
                  disabled
                  value="1"
                />
                <p>Coming Soon!</p>
                <span class="checkmark"></span>
              </label>
            </div>
          </div>
          <div>
            <!-- New layer in the future -->
          </div>
        </div>
        <script type="text/javascript">
          let boxes = document.querySelectorAll(
            "input[type=checkbox], video-selection "
          );
          boxes.forEach((b) => b.addEventListener("change", tick));
          function tick(e) {
            let state = e.target.checked; // save state of changed checkbox
            boxes.forEach((b) => (b.checked = false)); // clear all checkboxes
            e.target.checked = state; // restore state of changed checkbox
          }
        </script>
        <script>
          let subMenu = document.getElementById("subMenu");

          function toggleMenu() {
            subMenu.classList.toggle("open-menu");
          }
        </script>
      </section>
    </form>
  </body>
  <footer>
    <p>
      <span
        ><a href="{{ url_for('views.tos') }}">Terms of Service </a>
        <p></p>
        <a href="{{url_for('views.privacy')}}">Privacy Policy</a></span
      >
      © Copyright Viddat All Rights Reserved
    </p>
  </footer>
</html>

app/templates/custom_video_tutorial.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/styles/tutorial.css">
    <link rel="icon" type="image/x-icon" href="../static/favicon.ico">

    <!-- <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='styles/tutorial.css')}}" /> -->
    <title>Viddat Tutorial</title>
</head>
<body>
    <div id="navbar">
        <header>    
            <nav>
                <h1 id="viddat_button" onclick="window.location='{{ url_for('auth.sign_up')}}'" class="logo" style="font-size: 50px;">Viddat</h1>
        </header>
    </div>
    <div id="tutorial_container">
            <div id="tutorial_box">
                <button class="nav-button left" onclick="window.location='{{ url_for('views.tutorial', step =12)}}'"></button>
                <div id="tutorial_title">
                    <h1>You're All Set to Start Creating!</h1>
                </div>
                <div id="tutorial_body">

                    <p style="margin: auto; justify-content: center;">Start creating on the client page!</p>
                    <br>
                    <h1> <a href="{{url_for('client_page.client')}}">Welcome to Viddat!</a></h1>
                </div>
                <button class="nav-button right" onclick="window.location='{{ url_for('views.tutorial', step =14)}}'"></button>
            </div>
    </div>
</body>
</html>

app/templates/vid-dat_tutorial-4.html
{% extends "vid-dat_tutorial-template.html" %} {%block tutorial %}
<button
  class="nav-button left"
  onclick="window.location='{{ url_for('views.tutorial', step =3)}}'"
></button>
<div id="tutorial_title">
  <h1>Acquiring your Keys</h1>
</div>
<div id="tutorial_body">
  <p>Step 2: Next click on "Users" on the menu on the left.</p>
  <br />
  <img class="steps" src="../static/step2.png" alt="" />
</div>
<button
  class="nav-button right"
  onclick="window.location='{{ url_for('views.tutorial', step =5)}}'"
></button>
{%endblock%}